language: android
jdk: oraclejdk8
sudo: false

android:
  components:
  - platform-tools
  - tools
  - build-tools-27.0.3
  - android-23 # Android platform used by your alternative emulator
  - android-27
  - sys-img-armeabi-v7a-android-23
  - sys-img-armeabi-v7a-android-27
  
Extras
  - extra-android-m2repository
  - extra-google-m2repository  # Removed duplicated component
  
before_script:    
  - android list targets
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  
script: 
  - ./gradlew test
  - ./gradlew connectedAndroidTest
script: "./travis-build.sh"
